### ISSUE TITLE
upload the source rob [SERIOUS] [DO IT] [NOT JOKING]

### ISSUE THREAD

**Issue by HotPizzaYT** [RobvandenBerg/trashbattle#1]
do it

**Comment by HotPizzaYT** [comment]
As I said before, please, PLEASE for the love of god, upload it Rob. Everyday I grow more tired, more old that this game hasn't come out yet. And even many years back when I was just a wee lad in elementary I saw that the release date was far out of reach. And please, if you make it open source, allow people to contribute. It would be a pleasure. It sucks that this game never was, and I'm sure that you have the code yourself, as you said once in our Discord DMs

You said this

> I might release it yeah, since right now I've got no real plans on finishing it. I don't really like the networking model I used to program it, looking back

Will you stay true to your word? I don't know. But one thing is certain. It is 100% a good idea to do it, c'mon Rob just do it! There's nobody forcing you to do it (except me lol)

You should ask the 3DSPlaza Homebase server if you should bring Trash Battle back!

**Comment by RobvandenBerg** [comment]
Your wish has been granted. Source code uploaded.
